---
- name: setup ansible nodes
  hosts: all
  become: yes
  tasks:
    - name: Populate hostfiles
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['ansible_all_ipv4_addresses'][1] }} {{ hostvars[item]['inventory_hostname'] }} {{ hostvars[item]['inventory_hostname'] }}.rhce"
      delegate_to: localhost
      loop: 
        - node1
        - node2
      when: inventory_hostname == 'controller'
    - name: install tmux
      yum:
        name: 
          - vim
          - tmux
        state: present
    - name: set .vimrc
      copy:
        dest: /home/vagrant/.vimrc
        content: |
          set number hlsearch ai et sw=2 ts=2 
          syntax on
    - name: Set hostname to inventory_hostname
      command: hostnamectl set-hostname {{ inventory_hostname }}
      register: hostnamectl
    - name: reboot
      reboot:
      when: hostnamectl.changed and inventory_hostname in groups['nodes']
    - name: command
      command: shutdown -r 0
      when: inventory_hostname == 'controller'
