
Vagrant.configure("2") do |config|
 
    config.vm.box = "almalinux/8"
   
    config.vm.define "node1" do |machine|
      machine.vm.network "private_network", ip: "192.168.56.10"
    end
   
    config.vm.define "node2" do |machine|
      machine.vm.network "private_network", ip: "192.168.56.12"
    end
   
    config.vm.define 'controller' do |machine|
      machine.vm.network "private_network", ip: "192.168.56.13"
   
      machine.vm.provision :ansible_local do |ansible|
        ansible.playbook       = "playbook.yml"
        ansible.verbose        = true
        ansible.install        = true
        ansible.install_mode   = 'pip'
        ansible.limit          = "all" # or only "nodes" group, etc.
        ansible.inventory_path = "inventory"
      end
    end
   
  end