---
- name: setup ansible nodes
  hosts: all
  become: yes
  remote_user: vagrant
  vars:
    packages: 
      - tmux
      - vim
      - git
  tasks:
    - name: debug
      debug:
        msg: "{{ hostvars[item]['ansible_facts']}}"
      loop: "{{ groups['nodes'] }}"
      when: inventory_hostname == 'control'
    - name: Populate hostfiles
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['ansible_facts']['default_ipv4']['address'] }} {{ hostvars[item]['inventory_hostname'] }} {{ hostvars[item]['inventory_hostname'] }}.example.com"
      delegate_to: localhost
      loop: "{{ groups['nodes'] }}"
      when: inventory_hostname == 'control'
    - name: create user ansible
      user:
        name: ansible
        state: present
    - name: set .vimrc
      copy:
        dest: /home/ansible/.vimrc
        content: |
          set number hlsearch ai et sw=2 ts=2 
          syntax on
    - name: ensure /home/ansible/.ssh
      file:
        path: /home/ansible/.ssh
        mode: 0750
        owner: ansible
        group: ansible
        state: directory
    - name: enable passwordless sudo
      copy:
        dest: /etc/sudoers.d/ansible
        mode: 0400
        owner: root
        group: root
        content: "ansible ALL=(ALL) NOPASSWD: ALL"
    - name: create ansible inventory
      copy:
        dest: /home/ansible/inventory
        owner: ansible
        group: ansible
        content: |
          [nodes]
          {% for node in groups['nodes'] %}
          {{ node }}
          {% endfor %}
      delegate_to: localhost
      when: inventory_hostname == 'control'
    - name: copy ansible.cfg to /home/ansible
      copy:
        src: /vagrant/ansible.cfg
        dest: /home/ansible/.ansible.cfg
        owner: ansible
        group: ansible
        remote_src: yes
        mode: 0640
      delegate_to: localhost
      when: inventory_hostname == 'control'
    - name: regenerate pub key from control private key
      command: ssh-keygen -y -f /vagrant/.vagrant/machines/control/virtualbox/private_key
      register: public_key
      delegate_to: localhost
      when: inventory_hostname == 'control'
    - name: move private_key to /home/ansible/.ssh/id_rsa
      copy:
        src: /vagrant/.vagrant/machines/control/virtualbox/private_key
        dest: /home/ansible/.ssh/id_rsa
        mode: 0600
        owner: ansible
        group: ansible
      delegate_to: localhost
      when: inventory_hostname == 'control'
    - name: debug
      debug:
        var: hostvars['control'].public_key.stdout
    - name: add id_rsa.pub to authorized_keys file of nodes
      authorized_key:
        user: ansible
        key: "{{ hostvars['control'].public_key.stdout }}"
        state: present
    - name: Set hostname to inventory_hostname
      hostname: 
        name: "{{ inventory_hostname }}"
      register: hostname
    - name: reboot
      reboot:
      when: hostname.changed and inventory_hostname in groups['nodes']
    - name: command
      command: shutdown -r 0
      when: hostname.changed and inventory_hostname == 'control'