name: vagrant-up

on: 
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  schedule:
    - cron: "0 0 * * 5" # run every Friday at 00:00

jobs:
  vagrant-up:
    runs-on: macos10.15

    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: verify ansible lab works as expected
        run: vagrant ssh control -c "sudo -u ansible bash -c 'ansible nodes -m ping -b -u ansible'"
